(() => {
  const header=document.querySelector('.site-header');
  const toggle=document.querySelector('.menu-toggle');
  const menu=document.querySelector('.site-nav');
  const onScroll=()=>header?.classList.toggle('scrolled',window.scrollY>24);
  window.addEventListener('scroll',onScroll,{passive:true}); onScroll();
  toggle?.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));});
  menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle?.setAttribute('aria-expanded','false')}));

  const reveal=()=>document.querySelectorAll('.reveal').forEach(el=>el.classList.add('is-visible'));
  if('IntersectionObserver' in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));}else reveal();

  document.querySelectorAll('.gallery-item').forEach(btn=>btn.addEventListener('click',()=>{const lb=document.getElementById('lightbox'),img=document.getElementById('lightbox-image');if(!lb||!img)return;img.src=btn.dataset.src;img.alt=btn.querySelector('img')?.alt||'';lb.hidden=false;document.body.style.overflow='hidden';}));
  const closeLightbox=()=>{const lb=document.getElementById('lightbox');if(lb){lb.hidden=true;document.body.style.overflow='';}};
  document.querySelector('.lightbox-close')?.addEventListener('click',closeLightbox);document.getElementById('lightbox')?.addEventListener('click',e=>{if(e.target.id==='lightbox')closeLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLightbox()});

  const form=document.getElementById('quote-form');
  form?.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(form);const subject=`REAL IMPEX B2B Enquiry — ${fd.get('category')||'Textile Requirement'}`;const body=[`Name: ${fd.get('name')}`,`Company: ${fd.get('company')}`,`Country: ${fd.get('country')}`,`Email: ${fd.get('email')}`,`Phone / WhatsApp: ${fd.get('phone')}`,`Category: ${fd.get('category')}`,`Requirement: ${fd.get('requirement')}`,`Estimated Quantity: ${fd.get('quantity')}`,`Target Delivery Date: ${fd.get('delivery')}`,`Message: ${fd.get('message')}`].join('\n');window.location.href=`mailto:realsundar@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;const s=document.getElementById('form-status');if(s)s.textContent='Your email client should open with the enquiry details pre-filled.';});

  const DATA={
    'home-textiles':{eyebrow:'HOME TEXTILES',title:'Home textiles designed for comfort, repeatability and brand identity.',intro:'A broad home-textile family covering bedding, bath, decorative and furnishing made-ups. Final specifications are developed around the buyer brief.',image:'assets/images/products/prod-bed-linen.jpg',products:[
      ['Bed Sheets','Bed linen for everyday, premium and hospitality-adjacent collections.','Cotton / poly-cotton / blends','Single • Double • Queen • King • Custom','Plain, stripe, print, jacquard or buyer artwork','Custom GSM, weave, finish and packaging.'],
      ['Pillowcases','Matching or contrast pillowcases for coordinated bedding programs.','Cotton / poly-cotton / blends','Standard • King • Euro • Custom','Envelope, flap or zipper constructions','Colour matching, embroidery and labels.'],
      ['Duvet Covers','Duvet covers for retail, private label and contract collections.','Cotton / poly-cotton / linen blends','Single • Double • Queen • King • Custom','Plain, print, jacquard, sateen or percale','Corner ties, closures and packaging as required.'],
      ['Quilts & Blankets','Layered bedding and cover products for seasonal and premium ranges.','Cotton / microfiber / blended fills','Single • Double • Queen • King • Custom','Solid, printed or quilted constructions','Fill weight, quilting pattern and edge finish.'],
      ['Bath Towels & Bath Linen','Soft terry products for residential and premium bath collections.','Cotton terry / blended terry','Hand • Bath • Bath sheet • Face • Custom','Loop pile / dobby / jacquard','GSM, border, embroidery and pack configuration.'],
      ['Curtains, Cushions & Throws','Decorative made-ups for coordinated room collections.','Cotton / linen blends / polyester blends','Custom dimensions','Woven, printed, textured or quilted','Custom sizes, trims, labels and private label.']
    ],specs:[['Fabric','Cotton, poly-cotton, terry, bamboo, linen blends and other suitable options','Composition and blend ratio'],['GSM','Product dependent; selected during development','Target GSM'],['Weave','Percale, sateen, waffle, jacquard and other suitable structures','Construction'],['Colour','Standard colours or buyer-specific shades','Pantone / approved lab dip'],['Finish','Soft wash, wrinkle-resistant, antimicrobial or other applicable finishes','Finish requirement'],['Packaging','Bulk, retail-ready, private-label or buyer-specific','Pack ratio / labelling']]},
    'hospitality':{eyebrow:'HOSPITALITY LINEN',title:'Hotel linen engineered around appearance, wash performance and repeat orders.',intro:'A contract-focused family for hotels, resorts, serviced residences and hospitality buyers. Specifications are developed around laundering, durability, presentation and replacement cycles.',image:'assets/images/products/prod-hotel.jpg',products:[
      ['Hotel Bedsheets','Clean, repeatable bedding programs for rooms and contract supply.','Cotton / poly-cotton / blends','Single • Double • Queen • King • Custom','Plain / stripe / dobby / sateen / percale','Thread count, GSM, construction and laundering requirement.'],
      ['Hotel Pillowcases','Coordinated pillowcases designed for repeated commercial laundering.','Cotton / poly-cotton','Standard • King • Euro • Custom','Envelope / flap / custom closure','Packing, labelling and hotel-specific size.'],
      ['Duvet Covers','Room-set duvet covers for hospitality bedding programs.','Cotton / poly-cotton / blends','Single • Double • Queen • King','Plain / stripe / dobby / sateen','Ties, closure and laundering requirements.'],
      ['Bath Towels','Terry bath towels for rooms, spas and guest amenities.','Cotton terry / blended terry','Face • Hand • Bath • Bath sheet','Dobby / jacquard / border','GSM, absorbency target, embroidery and pack ratio.'],
      ['Bath Mats','Bathroom mats for guest-room and spa environments.','Cotton terry / woven / blended','Standard • Custom','Loop / dobby / textured','Anti-slip requirement where applicable.'],
      ['Table Linen & Made-Ups','Tablecloths, runners, napkins and coordinated hospitality textiles.','Cotton / linen blends / poly-cotton','Custom hotel dimensions','Plain / jacquard / printed','Colour, stain-performance requirements and packaging.']
    ],specs:[['Laundering','Commercial / industrial laundering requirements','Wash process and temperature'],['Durability','Construction selected for repeat use','Target lifecycle / replacement cycle'],['Colour','White, neutral or brand palette','Pantone / approved lab dip'],['GSM','Product dependent','Target GSM'],['Packaging','Hotel-set / bulk / private label','Pack ratio and carton marking']]},
    'hospital':{eyebrow:'HOSPITAL TEXTILES',title:'Institutional textiles focused on hygiene, practicality and repeatable specifications.',intro:'Hospital and institutional made-ups can be developed around laundering, comfort, construction and buyer-specific operational requirements. Regulatory or medical claims are not implied.',image:'assets/images/products/hospital-detail.jpg',products:[
      ['Hospital Bed Linen','Sheets and bed linen for institutional environments.','Cotton / poly-cotton','Single • Institutional standard • Custom','Plain / institutional constructions','Laundering, dimensional stability and labelling.'],
      ['Patient Gowns','Practical gowns for institutional use.','Cotton / poly-cotton / suitable blends','Adult / institutional / custom','Plain / printed / closure variants','Size grading, ties/closures and wash requirements.'],
      ['Hospital Pillow Covers','Protective and washable pillow covers for institutional bedding.','Cotton / poly-cotton','Institutional standard • Custom','Plain / flap / closure','Dimensional stability and packaging.'],
      ['Draw Sheets','Institutional bed made-ups for operational linen systems.','Cotton / poly-cotton / blends','Custom institutional sizes','Plain / reinforced constructions','Reinforcement and laundering requirement.'],
      ['Examination Linen','Textiles for examination and treatment environments.','Cotton / poly-cotton','Custom','Plain / functional constructions','Colour coding, size and wash requirements.'],
      ['Institutional Made-Ups','Custom textile components for healthcare and institutional programs.','Buyer-specified','Custom','Buyer-specific','Specification, packaging and documentation.']
    ],specs:[['Fabric','Cotton / poly-cotton / suitable institutional blends','Composition'],['Laundering','Defined according to buyer process','Wash temperature / process'],['Construction','Reinforcement and stitching based on use','Seam / stitch requirements'],['Colour','Institutional white or buyer-specified colours','Approved colour'],['Documentation','Buyer-required product documents','Document checklist']]},
    'kitchen':{eyebrow:'KITCHEN & DINING',title:'Kitchen and dining textiles that combine utility, presentation and private-label flexibility.',intro:'From daily-use kitchen towels to coordinated dining collections, this category supports functional products with custom colour, size, finishing and packaging.',image:'assets/images/products/prod-kitchen-linen.jpg',products:[
      ['Kitchen Towels','Everyday utility towels for retail, hospitality and private label.','Cotton / poly-cotton / linen blends','Approx. 30×50 cm • 40×60 cm • Custom','Plain / stripe / check / printed','GSM, loop, hanging tab and pack ratio.'],
      ['Tea Towels','Lightweight towels for kitchen and dining collections.','Cotton / linen blends','Approx. 45×65 cm • 50×70 cm • Custom','Plain / check / stripe / print','Weave, GSM and artwork.'],
      ['Table Covers','Tablecloths for residential and hospitality dining.','Cotton / poly-cotton / linen blends','Custom table dimensions','Plain / jacquard / printed','Drop length, hem, stain-performance requirement.'],
      ['Table Runners & Napkins','Coordinated dining accents for retail and hospitality.','Cotton / linen blends','Custom / standard dining sizes','Plain / embroidered / printed','Set configuration and packaging.'],
      ['Aprons','Kitchen and food-service aprons for institutional and retail programs.','Cotton / poly-cotton','Adult / custom','Plain / printed / contrast trim','Pocket, strap and logo placement.'],
      ['Oven Mitts & Made-Ups','Functional kitchen textile accessories.','Cotton / blended fabrics','Custom','Quilted / padded / printed','Padding, construction and packaging.']
    ],specs:[['Fabric','Cotton, poly-cotton, linen blends and suitable fabrics','Composition'],['GSM','Product dependent','Target GSM'],['Print','Screen / digital / buyer artwork where applicable','Artwork / repeat'],['Colour','Standard or custom','Pantone / lab dip'],['Packaging','Bulk / retail / private label','Pack ratio / barcode']]},
    'fabrics':{eyebrow:'FABRICS',title:'Fabric options for buyers who want control earlier in the product development process.',intro:'Fabric sourcing can be coordinated around construction, composition, GSM, weave, colour, finish and end-use. Exact availability is confirmed against the development brief.',image:'assets/images/products/fabric-detail.jpg',products:[
      ['Woven Cotton Fabrics','Versatile woven bases for bedding and made-ups.','Cotton','Buyer-specified GSM','Percale / sateen / plain / dobby / jacquard','Width, GSM, yarn and finishing.'],
      ['Poly-Cotton Fabrics','Practical blended constructions for durability and cost balance.','Cotton / polyester blends','Buyer-specified GSM','Plain / stripe / dobby','Blend ratio, width and finish.'],
      ['Terry Fabrics','Looped structures for towels and bath products.','Cotton terry / blended terry','Buyer-specified GSM','Single / double loop / dobby','Pile, GSM, absorbency and border.'],
      ['Bamboo / Linen Blend Options','Natural-fibre or blended directions for selected collections.','Bamboo / linen blends','Product dependent','Woven / blended structures','Composition and certification route where applicable.'],
      ['Microfiber / Flannel','Functional or seasonal fabric directions.','Microfiber / cotton flannel / blends','Product dependent','Brushed / smooth / printed','Weight, hand feel and finish.'],
      ['Jacquard / Sateen / Waffle','Higher visual or tactile differentiation for premium collections.','Cotton / blended bases','Product dependent','Jacquard / sateen / waffle','Pattern, GSM, colour and finishing.']
    ],specs:[['Composition','Cotton, poly-cotton, terry, bamboo, linen blends, microfiber, flannel','Blend ratio'],['GSM','Buyer-specific','Target GSM'],['Width','Selected according to end product','Usable width'],['Weave','Percale, sateen, waffle, jacquard and other structures','Construction'],['Colour','Standard or custom','Pantone / lab dip'],['Finish','Applicable finishing options','Finish specification']]},
    'custom':{eyebrow:'CUSTOM MADE-UPS & PRIVATE LABEL',title:'Turn a reference, sketch or specification into a coordinated textile product.',intro:'Custom development supports buyer-specific sizes, fabrics, colours, construction, finishes, labels and packaging. The development route depends on product complexity and approval requirements.',image:'assets/images/products/custom-detail.jpg',products:[
      ['Private-Label Bedding','Branded bedding collections for retailers and private-label programs.','Buyer-selected','Custom','Plain / print / jacquard / embroidery','Labels, packaging, barcode and assortment.'],
      ['Custom Cushions & Throws','Decorative products developed to a collection brief.','Cotton / linen blends / suitable fabrics','Custom','Woven / printed / embroidered / quilted','Insert, trim, label and pack.'],
      ['Custom Curtains','Room-setting products for residential and hospitality collections.','Cotton / polyester / blends','Custom','Plain / printed / textured','Header, lining and dimensions.'],
      ['Custom Hospitality Sets','Coordinated bed, bath and table sets.','Buyer-selected','Custom hotel dimensions','Coordinated colour / construction','Set packing and labelling.'],
      ['Institutional Made-Ups','Specialised products for healthcare, hospitality and institutional programs.','Buyer-selected','Custom','Functional constructions','Specification and documentation.'],
      ['Packaging & Branding','Buyer-specific labels, cartons, barcode and presentation systems.','Packaging materials','Custom','Retail / bulk / private label','Artwork, pack ratio and carton marks.']
    ],specs:[['Reference','Existing sample, sketch, tech pack or written brief','Source document'],['Size','Custom','Approved size chart'],['Fabric','Buyer-selected or developed','Composition / GSM'],['Colour','Standard or custom','Pantone / lab dip'],['Branding','Labels, embroidery, print, packaging','Artwork files'],['MOQ','Product and development dependent','Target quantity']]}
  };
  const imageMap={
      'Bed Sheets':'assets/images/products/prod-bed-linen.jpg','Pillowcases':'assets/images/products/prod-bath-linen.jpg','Duvet Covers':'assets/images/products/hero-home-textile.jpg','Quilts & Blankets':'assets/images/products/prod-home-furnishing.jpg','Bath Towels & Bath Linen':'assets/images/products/prod-bath-linen.jpg','Curtains, Cushions & Throws':'assets/images/products/prod-home-furnishing.jpg',
      'Hotel Bedsheets':'assets/images/products/prod-hotel.jpg','Hotel Pillowcases':'assets/images/products/prod-bath-linen.jpg','Duvet Covers':'assets/images/products/hero-home-textile.jpg','Bath Towels':'assets/images/products/prod-bath-linen.jpg','Bath Mats':'assets/images/products/prod-bath-linen.jpg','Table Linen & Made-Ups':'assets/images/products/prod-kitchen-linen.jpg',
      'Hospital Bed Linen':'assets/images/products/hospital-detail.jpg','Patient Gowns':'assets/images/products/hospital-detail.jpg','Hospital Pillow Covers':'assets/images/products/prod-bed-linen.jpg','Draw Sheets':'assets/images/products/hospital-detail.jpg','Examination Linen':'assets/images/products/hospital-detail.jpg','Institutional Made-Ups':'assets/images/products/custom-detail.jpg',
      'Kitchen Towels':'assets/images/products/prod-kitchen-linen.jpg','Tea Towels':'assets/images/products/prod-kitchen-linen.jpg','Table Covers':'assets/images/products/prod-home-furnishing.jpg','Table Runners & Napkins':'assets/images/products/prod-home-furnishing.jpg','Aprons':'assets/images/products/prod-kitchen-linen.jpg','Oven Mitts & Made-Ups':'assets/images/products/prod-kitchen-linen.jpg',
      'Woven Cotton Fabrics':'assets/images/products/fabric-detail.jpg','Poly-Cotton Fabrics':'assets/images/products/fabric-detail.jpg','Terry Fabrics':'assets/images/products/prod-bath-linen.jpg','Bamboo / Linen Blend Options':'assets/images/products/sustainable.jpg','Microfiber / Flannel':'assets/images/products/fabric-detail.jpg','Jacquard / Sateen / Waffle':'assets/images/products/custom-detail.jpg',
      'Private-Label Bedding':'assets/images/products/hero-home-textile.jpg','Custom Cushions & Throws':'assets/images/products/custom-detail.jpg','Custom Curtains':'assets/images/products/prod-home-furnishing.jpg','Custom Hospitality Sets':'assets/images/products/prod-hotel.jpg','Institutional Made-Ups':'assets/images/products/hospital-detail.jpg','Packaging & Branding':'assets/images/products/custom-detail.jpg'
    };
    const root=document.getElementById('product-detail');
  if(root){
    const key=new URLSearchParams(location.search).get('category')||'home-textiles'; const d=DATA[key]||DATA['home-textiles'];
    document.title=`${d.eyebrow} | REAL IMPEX`;
    document.getElementById('pd-eyebrow').textContent=d.eyebrow;document.getElementById('pd-title').innerHTML=d.title;document.getElementById('pd-intro').textContent=d.intro;document.getElementById('pd-family-title').textContent=d.eyebrow.replace(' & PRIVATE LABEL','');
    const wrap=document.getElementById('pd-products');wrap.innerHTML=d.products.map((p,i)=>`<article class="detail-card"><img src="${imageMap[p[0]]||d.image}" alt="${p[0]} editorial product image"><div class="detail-card-body"><h3>${p[0]}</h3><p>${p[1]}</p><div class="detail-meta"><div><small>Fabric</small><strong>${p[2]}</strong></div><div><small>Typical sizes</small><strong>${p[3]}</strong></div><div><small>Construction</small><strong>${p[4]}</strong></div><div><small>Customization</small><strong>${p[5]}</strong></div></div></div></article>`).join('');
    document.getElementById('pd-specs').innerHTML=d.specs.map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('');
  }
})();
